### ISSUE TITLE
Mapping NCBI SRA IDs to metadata

### ISSUE THREAD

**Issue by fantin-mesny** [anlebreton/Scripts_from_Zeng_Lebreton_et_al._2023#1]
Good morning,

I am willing to re-analyze some data from your publication.
I could download the reads from NCBI SRA, but cannot find in the publication which sample corresponds to OS or OM soil layers.
I found here the file `metatranscriptomique/0_metadata/metadata_all.txt`, but it does not provide the same IDs as the SRA metadata.
Could you please let me know how I can link the SRA IDs (Abies-x/Picea-x/Quercus-x, with x between 1 and 24) to the IDs in this table, or simply to soil layers OS/OM?

Many thanks, and best wishes,
Fantin Mesny

**Comment by anlebreton** [comment]
Hi Fantin, 

Can you provide me the metadata you got from SRA ? I can see the information you're looking for in the files names.

![screenshot](https://github.com/anlebreton/Scripts_from_Zeng_Lebreton_et_al._2023/assets/20325134/08698073-ba4a-45be-abb7-16c8223d9941)

Best,
Annie

**Comment by fantin-mesny** [comment]
Hi Annie,

Thanks! Suprising that they appear in search results.
I batch downloaded metadata associated to SRA runs of the bioproject. And these names are not in that table (see attached: [SraRunTable.txt](https://github.com/anlebreton/Scripts_from_Zeng_Lebreton_et_al._2023/files/13248514/SraRunTable.txt)).

Anyways, I can manage with search results, I guess.


Thanks again,
Fantin

**Comment by anlebreton** [comment]
Hi Fantin, 

I added a new column on the file `metatranscriptomique/0_metadata/metadata_all.tsv ` with the run number so you can merge these two metadata files. 

Best,
Annie
